import { LayoutModule } from '@angular/cdk/layout';
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import * as material from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    LayoutModule,
    material.MatToolbarModule,
    material.MatButtonModule,
    material.MatSidenavModule,
    material.MatIconModule,
    material.MatListModule,
    material.MatTabsModule,
    material.MatCardModule,
    material.MatExpansionModule,
    material.MatGridListModule,
    material.MatInputModule,
    material.MatFormFieldModule,
    material.MatRadioModule,
    material.MatSelectModule,
    material.MatDatepickerModule,
    material.MatMenuModule,
    material.MatTableModule,
    material.MatProgressBarModule,
    material.MatSnackBarModule,
    material.MatStepperModule,
    material.MatNativeDateModule,
    material.MatPaginatorModule,
    material.MatSortModule,
    material.MatTooltipModule,
    material.MatDialogModule,
    material.MatGridListModule,
    material.MatCardModule,
    material.MatIconModule,
    material.MatCheckboxModule,
    material.MatSlideToggleModule,
  ],
  exports: [
    LayoutModule,
    material.MatToolbarModule,
    material.MatButtonModule,
    material.MatSidenavModule,
    material.MatIconModule,
    material.MatListModule,
    material.MatTabsModule,
    material.MatCardModule,
    material.MatExpansionModule,
    material.MatFormFieldModule,
    material.MatGridListModule,
    material.MatRadioModule,
    material.MatSelectModule,
    material.MatDatepickerModule,
    material.MatMenuModule,
    material.MatInputModule,
    material.MatTableModule,
    material.MatProgressBarModule,
    material.MatSnackBarModule,
    material.MatStepperModule,
    material.MatNativeDateModule,
    material.MatPaginatorModule,
    material.MatSortModule,
    material.MatTooltipModule,
    material.MatDialogModule,
    material.MatCheckboxModule,
    material.MatSlideToggleModule
  ]
})
export class MaterialModule { }
